version: 2.1

jobs:
  "ci-trusty":
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/
    steps:
      - checkout
      - run: make --version
      - run:
          name: make docker-build-go
          command: make docker-build-go
workflows:
  version: 2
  build:
    jobs:
      - "ci-trusty"

